// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd7L0oxqL6jWI8UdQi6J5zsnji8nVGZLs',
    appId: '1:527017100609:web:1a2d7a9bf2fffcbe2f8dc0',
    messagingSenderId: '527017100609',
    projectId: 'gps-student-attendance',
    authDomain: 'gps-student-attendance.firebaseapp.com',
    storageBucket: 'gps-student-attendance.appspot.com',
    measurementId: 'G-8HNMRPBQ8J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvnpVnbAfQ_l29HPU_bUulwGjzb_uZmoA',
    appId: '1:527017100609:android:9f4fee82436b0c522f8dc0',
    messagingSenderId: '527017100609',
    projectId: 'gps-student-attendance',
    storageBucket: 'gps-student-attendance.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFxTHeLp11IYMC3201eMNGqZWbLpIXlPM',
    appId: '1:527017100609:ios:3ec7cf8163413b872f8dc0',
    messagingSenderId: '527017100609',
    projectId: 'gps-student-attendance',
    storageBucket: 'gps-student-attendance.appspot.com',
    iosBundleId: 'com.kodaTeck.gpsStudentAttendance',
  );

}